project:
  type: book

book:
  title: "Skrypt do kursy Analiza danych biologicznych i prezentacja wykresów"
  author: "Agnieszka Strzałka"
  search: true
  repo-url: https://github.com/astrzalka/Skrypt_jak_wykres
  chapters:
    - index.qmd
    - wczytanie_danych.qmd
    - histogram.qmd
    - boxplot.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt

editor: source

